### ISSUE TITLE
Auto repair armour durability when 50% self revive fail and infinite dying state time

### ISSUE THREAD

**Issue by HUYBUSSIN** [Cycro54/Revive_Me#14]
There is a small bug but I think it will affect the gameplay a lot, that is when reviving yourself and falling into 50% failure, the player will die and the armour equipment (except weapons) will be completely repaired, it happens very randomly and sometimes it happens and sometimes it doesn't. At the same time, there will be times when the death time will become infinite in some cases and the player cannot use both options to revive and stuck in the dying stage. 1.19.2 3.5.1

**Comment by Cycro54** [comment]
Oh man am I late! 

The armour thing sounds like a mod compatibility issue. 

As for the infinite timer bug, I most likely wrote some bad code somewhere.
I can't promise when I'll be able to fix these issues since I don't currently have access to my files, but it is on my to-do list.

As for fixing the infinite timer dealy, you can try:
-  /revivemefix command (it will just rerun the dying/revive code)
- switching in and out of creative mode
-  or giving the PlayerRevive mod a try, at least it won't be as buggy as my mod.

Srry for the late reply and ty for giving my mod a try!

**Comment by Cycro54** [comment]
Fixed in the latest versions, I have no idea what's with the healing armor, but I now have a different way to kill the player when  their timer runs out.

The infinite death thing is mostly a MC bug, but my /revivemefix command _should_ fix it now
